import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-500 p-4">
          <h1>header</h1>
        </header>
        {children}
        <footer>
          <p className="bg-slate-300 p-4">Footer</p>
        </footer>
      </body>
    </html>
  );
}
